name: CI

on: [push, workflow_dispatch]

jobs:

  license-compliance:
    runs-on: ubuntu-22.04

    container:
      image: licensefinder/license_finder

    steps:
      - uses: actions/checkout@v2

      - name: License check
        shell: bash
        run: |
          pwd
          #ls -lah
          whoami
          echo "${SHELL}"
          echo "${GITHUB_ENV}"
          env | grep HOME
          export HOME=/root
          echo "hit"
          env | grep HOME
          #ls -lah /root
          #ls -lah /github/home/
          #ls /usr/share/rvm/gems/ruby-3.1.1/bin/license_finder
          #. /root/.profile
          source /root/.profile
          license_finder

  # secret-scan:
  #   runs-on: ubuntu-22.04

  #   container:
  #     image: zricethezav/gitleaks:v8.2.4

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Secret scan
  #       run: |
  #         gitleaks detect --redact -v

  # build:
  #   runs-on: ubuntu-22.04

  #   container:
  #     image: golang:1.14

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build package
  #       run: |
  #         go build
