name: CI

on: [push, workflow_dispatch]

jobs:

  # license-compliance:
  #   runs-on: ubuntu-22.04

  #   container:
  #     image: licensefinder/license_finder

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: License check
  #       shell: bash
  #       run: |
  #         export HOME=/root
  #         source /root/.profile
  #         license_finder

  # secret-scan:
  #   runs-on: ubuntu-22.04

  #   container:
  #     image: zricethezav/gitleaks:v8.2.4
  #     options: --entrypoint "" --user root

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Secret scan
  #       shell: bash
  #       run: |
  #         gitleaks detect --redact -v

  build:
    runs-on: ubuntu-22.04

    container:
      image: golang:1.19.1

    steps:
      - uses: actions/checkout@v2

      - name: Build package
        shell: bash
        run: |
          GOOS=linux GOARCH=amd64 go build -o self-cli-linux-amd64
          ls -lah
